#include <gtest/gtest.h>
#include <random>
#include <vector>
#include <algorithm>
#include <windows.h>
#include "Hopkroft.hpp"

TEST(HopcroftKarp, simpleSeperateMatching) {
    std::vector<int> aSide;
    aSide.push_back(0);
    aSide.push_back(1);
    std::vector<int> bSide;
    bSide.push_back(2);
    bSide.push_back(3);
    std::vector<std::pair<int, int>> edges;
    edges.push_back({ 0, 2 });
    edges.push_back({ 1, 3 });

    std::vector<std::pair<int, int>> out = fish(aSide, bSide, edges);

    EXPECT_EQ(out.size(), 2);
}

TEST(HopcroftKarp, simpleInterconnectedMatching) {
    std::vector<int> aSide;
    aSide.push_back(0);
    aSide.push_back(1);
    std::vector<int> bSide;
    bSide.push_back(2);
    bSide.push_back(3);
    std::vector<std::pair<int, int>> edges;
    edges.push_back({ 0, 2 });
    edges.push_back({ 1, 3 });
    edges.push_back({ 0, 3 });
    edges.push_back({ 1, 2 });

    std::vector<std::pair<int, int>> out = fish(aSide, bSide, edges);
    
    EXPECT_EQ(out.size(), 2);
}

TEST(HopcroftKarp, simpleImbalancedMatching) {
    std::vector<int> aSide;
    aSide.push_back(0);
    aSide.push_back(1);
    std::vector<int> bSide;
    bSide.push_back(2);
    bSide.push_back(3);
    bSide.push_back(4);
    std::vector<std::pair<int, int>> edges;
    edges.push_back({ 0, 2 });
    edges.push_back({ 1, 3 });
    edges.push_back({ 0, 3 });
    edges.push_back({ 1, 2 });
    edges.push_back({ 1, 4 });

    std::vector<std::pair<int, int>> out = fish(aSide, bSide, edges);

    EXPECT_EQ(out.size(), 2);
}

TEST(HopcroftKarp, largeImBalancedMatching) {
    std::vector<int> aSide;
    aSide.push_back(0);
    aSide.push_back(1);
    std::vector<int> bSide;
    bSide.push_back(2);
    bSide.push_back(3);
    bSide.push_back(4);
    bSide.push_back(5);
    bSide.push_back(6);
    bSide.push_back(7);
    bSide.push_back(8);
    bSide.push_back(9);
    bSide.push_back(10);
    bSide.push_back(11);
    bSide.push_back(12);
    bSide.push_back(13);
    bSide.push_back(14);
    bSide.push_back(15);
    bSide.push_back(16);
    bSide.push_back(17);
    bSide.push_back(18);
    bSide.push_back(19);
    std::vector<std::pair<int, int>> edges;
    edges.push_back({ 0, 2 });
    edges.push_back({ 1, 3 });
    edges.push_back({ 0, 3 });
    edges.push_back({ 1, 2 });

    std::vector<std::pair<int, int>> out = fish(aSide, bSide, edges);

    EXPECT_EQ(out.size(), 2);
}


TEST(HopcroftKarp, largeBalancedMatching) {
    std::vector<int> aSide;
    aSide.push_back(0);
    aSide.push_back(1);
    aSide.push_back(2);
    aSide.push_back(3);
    aSide.push_back(4);
    aSide.push_back(5);
    aSide.push_back(6);
    aSide.push_back(7);
    std::vector<int> bSide;
    aSide.push_back(8);
    bSide.push_back(9);
    bSide.push_back(10);
    bSide.push_back(11);
    bSide.push_back(12);
    bSide.push_back(13);
    bSide.push_back(14);
    bSide.push_back(15);
    std::vector<std::pair<int, int>> edges;
    edges.push_back({ 3, 10 });
    edges.push_back({ 0, 8 });
    edges.push_back({ 1, 9 });
    edges.push_back({ 2, 10 });
    edges.push_back({ 3, 11 });
    edges.push_back({ 4, 12 });
    edges.push_back({ 5, 13 });
    edges.push_back({ 6, 14 });
    edges.push_back({ 7, 15 });

    std::vector<std::pair<int, int>> out = fish(aSide, bSide, edges);

    EXPECT_EQ(out.size(), 8);
}

TEST(HopcroftKarp, massive) {
    std::vector<int> aSide;
    std::vector<int> bSide;
    aSide.push_back(0);
    aSide.push_back(1);
    aSide.push_back(2);
    aSide.push_back(3);
    aSide.push_back(4);
    aSide.push_back(5);
    aSide.push_back(6);
    aSide.push_back(7);
    aSide.push_back(8);
    aSide.push_back(9);
    aSide.push_back(10);
    aSide.push_back(11);
    aSide.push_back(12);
    aSide.push_back(13);
    aSide.push_back(14);
    aSide.push_back(15);
    aSide.push_back(16);
    aSide.push_back(17);
    aSide.push_back(18);
    aSide.push_back(19);
    bSide.push_back(19);
    bSide.push_back(20);
    bSide.push_back(21);
    bSide.push_back(22);
    bSide.push_back(23);
    bSide.push_back(24);
    bSide.push_back(25);
    bSide.push_back(26);
    bSide.push_back(27);
    bSide.push_back(28);
    bSide.push_back(29);
    bSide.push_back(30);
    bSide.push_back(31);
    bSide.push_back(32);
    bSide.push_back(33);
    bSide.push_back(34);
    bSide.push_back(35);
    bSide.push_back(36);
    bSide.push_back(37);
    bSide.push_back(38);
    std::vector<std::pair<int, int>> edges;
    edges.push_back({ 0 , 19 });
    edges.push_back({ 0 , 20 });
    edges.push_back({ 0 , 21 });
    edges.push_back({ 0 , 22 });
    edges.push_back({ 0 , 23 });
    edges.push_back({ 0 , 24 });
    edges.push_back({ 0 , 25 });
    edges.push_back({ 0 , 26 });
    edges.push_back({ 0 , 27 });
    edges.push_back({ 0 , 28 });
    edges.push_back({ 0 , 29 });
    edges.push_back({ 0 , 30 });
    edges.push_back({ 0 , 31 });
    edges.push_back({ 0 , 32 });
    edges.push_back({ 0 , 33 });
    edges.push_back({ 0 , 34 });
    edges.push_back({ 0 , 35 });
    edges.push_back({ 0 , 36 });
    edges.push_back({ 0 , 37 });
    edges.push_back({ 0 , 38 });
    edges.push_back({ 1 , 19 });
    edges.push_back({ 1 , 20 });
    edges.push_back({ 1 , 21 });
    edges.push_back({ 1 , 22 });
    edges.push_back({ 1 , 23 });
    edges.push_back({ 1 , 24 });
    edges.push_back({ 1 , 25 });
    edges.push_back({ 1 , 26 });
    edges.push_back({ 1 , 27 });
    edges.push_back({ 1 , 28 });
    edges.push_back({ 1 , 29 });
    edges.push_back({ 1 , 30 });
    edges.push_back({ 1 , 31 });
    edges.push_back({ 1 , 32 });
    edges.push_back({ 1 , 33 });
    edges.push_back({ 1 , 34 });
    edges.push_back({ 1 , 35 });
    edges.push_back({ 1 , 36 });
    edges.push_back({ 1 , 37 });
    edges.push_back({ 1 , 38 });
    edges.push_back({ 2 , 19 });
    edges.push_back({ 2 , 20 });
    edges.push_back({ 2 , 21 });
    edges.push_back({ 2 , 22 });
    edges.push_back({ 2 , 23 });
    edges.push_back({ 2 , 24 });
    edges.push_back({ 2 , 25 });
    edges.push_back({ 2 , 26 });
    edges.push_back({ 2 , 27 });
    edges.push_back({ 2 , 28 });
    edges.push_back({ 2 , 29 });
    edges.push_back({ 2 , 30 });
    edges.push_back({ 2 , 31 });
    edges.push_back({ 2 , 32 });
    edges.push_back({ 2 , 33 });
    edges.push_back({ 2 , 34 });
    edges.push_back({ 2 , 35 });
    edges.push_back({ 2 , 36 });
    edges.push_back({ 2 , 37 });
    edges.push_back({ 2 , 38 });
    edges.push_back({ 3 , 19 });
    edges.push_back({ 3 , 20 });
    edges.push_back({ 3 , 21 });
    edges.push_back({ 3 , 22 });
    edges.push_back({ 3 , 23 });
    edges.push_back({ 3 , 24 });
    edges.push_back({ 3 , 25 });
    edges.push_back({ 3 , 26 });
    edges.push_back({ 3 , 27 });
    edges.push_back({ 3 , 28 });
    edges.push_back({ 3 , 29 });
    edges.push_back({ 3 , 30 });
    edges.push_back({ 3 , 31 });
    edges.push_back({ 3 , 32 });
    edges.push_back({ 3 , 33 });
    edges.push_back({ 3 , 34 });
    edges.push_back({ 3 , 35 });
    edges.push_back({ 3 , 36 });
    edges.push_back({ 3 , 37 });
    edges.push_back({ 3 , 38 });
    edges.push_back({ 4 , 19 });
    edges.push_back({ 4 , 20 });
    edges.push_back({ 4 , 21 });
    edges.push_back({ 4 , 22 });
    edges.push_back({ 4 , 23 });
    edges.push_back({ 4 , 24 });
    edges.push_back({ 4 , 25 });
    edges.push_back({ 4 , 26 });
    edges.push_back({ 4 , 27 });
    edges.push_back({ 4 , 28 });
    edges.push_back({ 4 , 29 });
    edges.push_back({ 4 , 30 });
    edges.push_back({ 4 , 31 });
    edges.push_back({ 4 , 32 });
    edges.push_back({ 4 , 33 });
    edges.push_back({ 4 , 34 });
    edges.push_back({ 4 , 35 });
    edges.push_back({ 4 , 36 });
    edges.push_back({ 4 , 37 });
    edges.push_back({ 4 , 38 });
    edges.push_back({ 5 , 19 });
    edges.push_back({ 5 , 20 });
    edges.push_back({ 5 , 21 });
    edges.push_back({ 5 , 22 });
    edges.push_back({ 5 , 23 });
    edges.push_back({ 5 , 24 });
    edges.push_back({ 5 , 25 });
    edges.push_back({ 5 , 26 });
    edges.push_back({ 5 , 27 });
    edges.push_back({ 5 , 28 });
    edges.push_back({ 5 , 29 });
    edges.push_back({ 5 , 30 });
    edges.push_back({ 5 , 31 });
    edges.push_back({ 5 , 32 });
    edges.push_back({ 5 , 33 });
    edges.push_back({ 5 , 34 });
    edges.push_back({ 5 , 35 });
    edges.push_back({ 5 , 36 });
    edges.push_back({ 5 , 37 });
    edges.push_back({ 5 , 38 });
    edges.push_back({ 6 , 19 });
    edges.push_back({ 6 , 20 });
    edges.push_back({ 6 , 21 });
    edges.push_back({ 6 , 22 });
    edges.push_back({ 6 , 23 });
    edges.push_back({ 6 , 24 });
    edges.push_back({ 6 , 25 });
    edges.push_back({ 6 , 26 });
    edges.push_back({ 6 , 27 });
    edges.push_back({ 6 , 28 });
    edges.push_back({ 6 , 29 });
    edges.push_back({ 6 , 30 });
    edges.push_back({ 6 , 31 });
    edges.push_back({ 6 , 32 });
    edges.push_back({ 6 , 33 });
    edges.push_back({ 6 , 34 });
    edges.push_back({ 6 , 35 });
    edges.push_back({ 6 , 36 });
    edges.push_back({ 6 , 37 });
    edges.push_back({ 6 , 38 });
    edges.push_back({ 7 , 19 });
    edges.push_back({ 7 , 20 });
    edges.push_back({ 7 , 21 });
    edges.push_back({ 7 , 22 });
    edges.push_back({ 7 , 23 });
    edges.push_back({ 7 , 24 });
    edges.push_back({ 7 , 25 });
    edges.push_back({ 7 , 26 });
    edges.push_back({ 7 , 27 });
    edges.push_back({ 7 , 28 });
    edges.push_back({ 7 , 29 });
    edges.push_back({ 7 , 30 });
    edges.push_back({ 7 , 31 });
    edges.push_back({ 7 , 32 });
    edges.push_back({ 7 , 33 });
    edges.push_back({ 7 , 34 });
    edges.push_back({ 7 , 35 });
    edges.push_back({ 7 , 36 });
    edges.push_back({ 7 , 37 });
    edges.push_back({ 7 , 38 });
    edges.push_back({ 8 , 19 });
    edges.push_back({ 8 , 20 });
    edges.push_back({ 8 , 21 });
    edges.push_back({ 8 , 22 });
    edges.push_back({ 8 , 23 });
    edges.push_back({ 8 , 24 });
    edges.push_back({ 8 , 25 });
    edges.push_back({ 8 , 26 });
    edges.push_back({ 8 , 27 });
    edges.push_back({ 8 , 28 });
    edges.push_back({ 8 , 29 });
    edges.push_back({ 8 , 30 });
    edges.push_back({ 8 , 31 });
    edges.push_back({ 8 , 32 });
    edges.push_back({ 8 , 33 });
    edges.push_back({ 8 , 34 });
    edges.push_back({ 8 , 35 });
    edges.push_back({ 8 , 36 });
    edges.push_back({ 8 , 37 });
    edges.push_back({ 8 , 38 });
    edges.push_back({ 9 , 19 });
    edges.push_back({ 9 , 20 });
    edges.push_back({ 9 , 21 });
    edges.push_back({ 9 , 22 });
    edges.push_back({ 9 , 23 });
    edges.push_back({ 9 , 24 });
    edges.push_back({ 9 , 25 });
    edges.push_back({ 9 , 26 });
    edges.push_back({ 9 , 27 });
    edges.push_back({ 9 , 28 });
    edges.push_back({ 9 , 29 });
    edges.push_back({ 9 , 30 });
    edges.push_back({ 9 , 31 });
    edges.push_back({ 9 , 32 });
    edges.push_back({ 9 , 33 });
    edges.push_back({ 9 , 34 });
    edges.push_back({ 9 , 35 });
    edges.push_back({ 9 , 36 });
    edges.push_back({ 9 , 37 });
    edges.push_back({ 9 , 38 });
    edges.push_back({ 10 , 19 });
    edges.push_back({ 10 , 20 });
    edges.push_back({ 10 , 21 });
    edges.push_back({ 10 , 22 });
    edges.push_back({ 10 , 23 });
    edges.push_back({ 10 , 24 });
    edges.push_back({ 10 , 25 });
    edges.push_back({ 10 , 26 });
    edges.push_back({ 10 , 27 });
    edges.push_back({ 10 , 28 });
    edges.push_back({ 10 , 29 });
    edges.push_back({ 10 , 30 });
    edges.push_back({ 10 , 31 });
    edges.push_back({ 10 , 32 });
    edges.push_back({ 10 , 33 });
    edges.push_back({ 10 , 34 });
    edges.push_back({ 10 , 35 });
    edges.push_back({ 10 , 36 });
    edges.push_back({ 10 , 37 });
    edges.push_back({ 10 , 38 });
    edges.push_back({ 11 , 19 });
    edges.push_back({ 11 , 20 });
    edges.push_back({ 11 , 21 });
    edges.push_back({ 11 , 22 });
    edges.push_back({ 11 , 23 });
    edges.push_back({ 11 , 24 });
    edges.push_back({ 11 , 25 });
    edges.push_back({ 11 , 26 });
    edges.push_back({ 11 , 27 });
    edges.push_back({ 11 , 28 });
    edges.push_back({ 11 , 29 });
    edges.push_back({ 11 , 30 });
    edges.push_back({ 11 , 31 });
    edges.push_back({ 11 , 32 });
    edges.push_back({ 11 , 33 });
    edges.push_back({ 11 , 34 });
    edges.push_back({ 11 , 35 });
    edges.push_back({ 11 , 36 });
    edges.push_back({ 11 , 37 });
    edges.push_back({ 11 , 38 });
    edges.push_back({ 12 , 19 });
    edges.push_back({ 12 , 20 });
    edges.push_back({ 12 , 21 });
    edges.push_back({ 12 , 22 });
    edges.push_back({ 12 , 23 });
    edges.push_back({ 12 , 24 });
    edges.push_back({ 12 , 25 });
    edges.push_back({ 12 , 26 });
    edges.push_back({ 12 , 27 });
    edges.push_back({ 12 , 28 });
    edges.push_back({ 12 , 29 });
    edges.push_back({ 12 , 30 });
    edges.push_back({ 12 , 31 });
    edges.push_back({ 12 , 32 });
    edges.push_back({ 12 , 33 });
    edges.push_back({ 12 , 34 });
    edges.push_back({ 12 , 35 });
    edges.push_back({ 12 , 36 });
    edges.push_back({ 12 , 37 });
    edges.push_back({ 12 , 38 });
    edges.push_back({ 13 , 19 });
    edges.push_back({ 13 , 20 });
    edges.push_back({ 13 , 21 });
    edges.push_back({ 13 , 22 });
    edges.push_back({ 13 , 23 });
    edges.push_back({ 13 , 24 });
    edges.push_back({ 13 , 25 });
    edges.push_back({ 13 , 26 });
    edges.push_back({ 13 , 27 });
    edges.push_back({ 13 , 28 });
    edges.push_back({ 13 , 29 });
    edges.push_back({ 13 , 30 });
    edges.push_back({ 13 , 31 });
    edges.push_back({ 13 , 32 });
    edges.push_back({ 13 , 33 });
    edges.push_back({ 13 , 34 });
    edges.push_back({ 13 , 35 });
    edges.push_back({ 13 , 36 });
    edges.push_back({ 13 , 37 });
    edges.push_back({ 13 , 38 });
    edges.push_back({ 14 , 19 });
    edges.push_back({ 14 , 20 });
    edges.push_back({ 14 , 21 });
    edges.push_back({ 14 , 22 });
    edges.push_back({ 14 , 23 });
    edges.push_back({ 14 , 24 });
    edges.push_back({ 14 , 25 });
    edges.push_back({ 14 , 26 });
    edges.push_back({ 14 , 27 });
    edges.push_back({ 14 , 28 });
    edges.push_back({ 14 , 29 });
    edges.push_back({ 14 , 30 });
    edges.push_back({ 14 , 31 });
    edges.push_back({ 14 , 32 });
    edges.push_back({ 14 , 33 });
    edges.push_back({ 14 , 34 });
    edges.push_back({ 14 , 35 });
    edges.push_back({ 14 , 36 });
    edges.push_back({ 14 , 37 });
    edges.push_back({ 14 , 38 });
    edges.push_back({ 15 , 19 });
    edges.push_back({ 15 , 20 });
    edges.push_back({ 15 , 21 });
    edges.push_back({ 15 , 22 });
    edges.push_back({ 15 , 23 });
    edges.push_back({ 15 , 24 });
    edges.push_back({ 15 , 25 });
    edges.push_back({ 15 , 26 });
    edges.push_back({ 15 , 27 });
    edges.push_back({ 15 , 28 });
    edges.push_back({ 15 , 29 });
    edges.push_back({ 15 , 30 });
    edges.push_back({ 15 , 31 });
    edges.push_back({ 15 , 32 });
    edges.push_back({ 15 , 33 });
    edges.push_back({ 15 , 34 });
    edges.push_back({ 15 , 35 });
    edges.push_back({ 15 , 36 });
    edges.push_back({ 15 , 37 });
    edges.push_back({ 15 , 38 });
    edges.push_back({ 16 , 19 });
    edges.push_back({ 16 , 20 });
    edges.push_back({ 16 , 21 });
    edges.push_back({ 16 , 22 });
    edges.push_back({ 16 , 23 });
    edges.push_back({ 16 , 24 });
    edges.push_back({ 16 , 25 });
    edges.push_back({ 16 , 26 });
    edges.push_back({ 16 , 27 });
    edges.push_back({ 16 , 28 });
    edges.push_back({ 16 , 29 });
    edges.push_back({ 16 , 30 });
    edges.push_back({ 16 , 31 });
    edges.push_back({ 16 , 32 });
    edges.push_back({ 16 , 33 });
    edges.push_back({ 16 , 34 });
    edges.push_back({ 16 , 35 });
    edges.push_back({ 16 , 36 });
    edges.push_back({ 16 , 37 });
    edges.push_back({ 16 , 38 });
    edges.push_back({ 17 , 19 });
    edges.push_back({ 17 , 20 });
    edges.push_back({ 17 , 21 });
    edges.push_back({ 17 , 22 });
    edges.push_back({ 17 , 23 });
    edges.push_back({ 17 , 24 });
    edges.push_back({ 17 , 25 });
    edges.push_back({ 17 , 26 });
    edges.push_back({ 17 , 27 });
    edges.push_back({ 17 , 28 });
    edges.push_back({ 17 , 29 });
    edges.push_back({ 17 , 30 });
    edges.push_back({ 17 , 31 });
    edges.push_back({ 17 , 32 });
    edges.push_back({ 17 , 33 });
    edges.push_back({ 17 , 34 });
    edges.push_back({ 17 , 35 });
    edges.push_back({ 17 , 36 });
    edges.push_back({ 17 , 37 });
    edges.push_back({ 17 , 38 });
    edges.push_back({ 18 , 19 });
    edges.push_back({ 18 , 20 });
    edges.push_back({ 18 , 21 });
    edges.push_back({ 18 , 22 });
    edges.push_back({ 18 , 23 });
    edges.push_back({ 18 , 24 });
    edges.push_back({ 18 , 25 });
    edges.push_back({ 18 , 26 });
    edges.push_back({ 18 , 27 });
    edges.push_back({ 18 , 28 });
    edges.push_back({ 18 , 29 });
    edges.push_back({ 18 , 30 });
    edges.push_back({ 18 , 31 });
    edges.push_back({ 18 , 32 });
    edges.push_back({ 18 , 33 });
    edges.push_back({ 18 , 34 });
    edges.push_back({ 18 , 35 });
    edges.push_back({ 18 , 36 });
    edges.push_back({ 18 , 37 });
    edges.push_back({ 18 , 38 });
    edges.push_back({ 19 , 19 });
    edges.push_back({ 19 , 20 });
    edges.push_back({ 19 , 21 });
    edges.push_back({ 19 , 22 });
    edges.push_back({ 19 , 23 });
    edges.push_back({ 19 , 24 });
    edges.push_back({ 19 , 25 });
    edges.push_back({ 19 , 26 });
    edges.push_back({ 19 , 27 });
    edges.push_back({ 19 , 28 });
    edges.push_back({ 19 , 29 });
    edges.push_back({ 19 , 30 });
    edges.push_back({ 19 , 31 });
    edges.push_back({ 19 , 32 });
    edges.push_back({ 19 , 33 });
    edges.push_back({ 19 , 34 });
    edges.push_back({ 19 , 35 });
    edges.push_back({ 19 , 36 });
    edges.push_back({ 19 , 37 });
    edges.push_back({ 19 , 38 });

    std::vector<std::pair<int, int>> out = fish(aSide, bSide, edges);

    EXPECT_EQ(out.size(), 20);
}

//main
int CALLBACK WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR pCmdLine, int nCmdShow) {
    ::testing::InitGoogleTest();
    std::cout << "hello world";
    return RUN_ALL_TESTS();
}